version: "3"
services:
    web:
        build: .
        command: bash -c "flask db upgrade && python run.py"
        ports:
            - 5001:5001
        environment:
            - FLASK_APP=run.py
        env_file:
            - env.list
        depends_on:
            db:
                condition: service_started
            redis:
                condition: service_started
    db:
        image: postgres
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=bp_db
        ports:
            - 5432:5432
        volumes:
            - ./db_data:/var/lib/postgresql/data
    redis:
        image: redis
        ports:
            - 6379:6379
        command: redis-server --appendonly yes
        volumes:
            - ./redis_data:/data

volumes:
    db_data:
    redis_data:
